### ISSUE TITLE
Update SUNDIALS support to version 2.6

### ISSUE THREAD

**Issue by mwest1066** [compdyn/partmc#33]

**Comment by slayoo** [comment]
for the record, since version 4.1.0 of Sundials (Feb 2019): "The implementation header file cvode impl.h is no longer installed. This means users who are directly manipulating the CVodeMem structure will need to update their code to use cvode’s public API."

This breaks compilation:

```
[  1%] Building C object CMakeFiles/partmclib.dir/src/condense_solver.c.o
/data/keeling/a/sarabas/devel/partmc/src/condense_solver.c:15:10: fatal error: cvode/cvode_impl.h: No such file or directory
   15 | #include <cvode/cvode_impl.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```

Related FEniCS issues:
- https://bitbucket.org/fenics-project/dolfin/issues/1067/cv_functional-cv_newton-cv_adams-not
- https://aur.archlinux.org/packages/dolfin/?O=10&PP=10
